### ISSUE TITLE
source_mixing_function: 'chain'  seems to not work

### ISSUE THREAD

**Issue by hayden-t** [EugeneDae/VLC-Scheduler#22]
tried this option with the win build hosted, and it seems to have no effect, just always doing zip sort

**Comment by hayden-t** [comment]
```
sources:
    - path: Z:\Video\_New\355
      item_play_duration: 20
    - path: Z:\Video\_New\aaa
      item_play_duration: 20
    - path: Z:\Video\_New\fff
      item_play_duration: 20 
      
source_mixing_function: 'chain'      
media_extensions: ['.mp4', '.avi', '.mkv']

vlc:
    # Path to VLC
    path: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'
```
