### ISSUE TITLE
Schedule for different times of day

### ISSUE THREAD

**Issue by ctindia2009** [EugeneDae/VLC-Scheduler#24]
i want to add different time for different folder how it possible

- like morning video
- afternoon video
- evening video etc

it is possible in one yaml file

**Comment by EugeneDae** [comment]
Create three folders and three sources, like so:

```
sources:
    - path: C:\Users\Administrator\Desktop\Videos\Morning
      playing_time: 09:00-12:00
    - path: C:\Users\Administrator\Desktop\Videos\Afternoon
      playing_time: 12:00-18:00
    - path: C:\Users\Administrator\Desktop\Videos\Evening
      playing_time: 18:00-22:00
```
